// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzYKl4UD4iWbqehBrdVD4WhUfQYv0UEPA',
    appId: '1:845010457996:web:45256a06e02180250eb2a9',
    messagingSenderId: '845010457996',
    projectId: 'millennium-hub',
    authDomain: 'millennium-hub.firebaseapp.com',
    storageBucket: 'millennium-hub.firebasestorage.app',
    measurementId: 'G-75Q1FGWDZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpWRSqFSvJKJbgLCLEdcqWSdDIRjh2--Q',
    appId: '1:845010457996:android:f6364277c67505ce0eb2a9',
    messagingSenderId: '845010457996',
    projectId: 'millennium-hub',
    storageBucket: 'millennium-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrtIIc_7Fe60L5Q3fAsnMY-YX9hAdTyMs',
    appId: '1:845010457996:ios:f3355f3b9b4e0ec70eb2a9',
    messagingSenderId: '845010457996',
    projectId: 'millennium-hub',
    storageBucket: 'millennium-hub.firebasestorage.app',
    iosBundleId: 'com.example.lifeHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrtIIc_7Fe60L5Q3fAsnMY-YX9hAdTyMs',
    appId: '1:845010457996:ios:f3355f3b9b4e0ec70eb2a9',
    messagingSenderId: '845010457996',
    projectId: 'millennium-hub',
    storageBucket: 'millennium-hub.firebasestorage.app',
    iosBundleId: 'com.example.lifeHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzYKl4UD4iWbqehBrdVD4WhUfQYv0UEPA',
    appId: '1:845010457996:web:30106064b9edc07c0eb2a9',
    messagingSenderId: '845010457996',
    projectId: 'millennium-hub',
    authDomain: 'millennium-hub.firebaseapp.com',
    storageBucket: 'millennium-hub.firebasestorage.app',
    measurementId: 'G-HBR4JPW35H',
  );
}
